conve:
  convolution_bias: false
  entity_embedder:
    dropout: 0.4119570416445243
    regularize_weight: 1.3263961094628973e-15
  feature_map_dropout: 0.37379553816344435
  projection_dropout: 0.15571198484648494
  relation_embedder:
    dropout: -0.3276884737810202
    regularize_weight: 5.659599156270529e-15
  round_dim: true
dataset:
  name: /var/scratch/vcc500/kge-iclr20/data_dumps/mutag
  num_entities: 15260
  num_relations: 14
entity_ranking:
  metrics_per:
    relation_type: true
eval:
  batch_size: 256
import:
- conve
- reciprocal_relations_model
lookup_embedder:
  dim: 128
  initialize: xavier_uniform_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.04518432475440056
    uniform_:
      a: -0.9663815133488024
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  regularize: ''
model: reciprocal_relations_model
negative_sampling:
  implementation: batch
reciprocal_relations_model:
  base_model:
    entity_embedder:
      dim: 128
    relation_embedder:
      dim: 128
train:
  auto_correct: true
  batch_size: 128
  loss: bce
  loss_arg: 0.0
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 10
    threshold: 0.0001
  max_epochs: 400
  optimizer: Adam
  optimizer_args:
    lr: 0.012193621116131119
  type: 1vsAll
valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10

