dataset:
  name: aifb
  num_entities: 8280
  num_relations: 47
entity_ranking:
  metrics_per:
    relation_type: true
eval:
  batch_size: 256
import:
- rescal
- reciprocal_relations_model
lookup_embedder:
  dim: 256
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.00011738889797601787
    uniform_:
      a: -0.788178667059446
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  regularize_args:
    p: 3
model: reciprocal_relations_model
negative_sampling:
  implementation: batch
reciprocal_relations_model:
  base_model:
    relation_embedder:
      dim: 65536
    type: rescal
rescal:
  entity_embedder:
    dropout: 0.42258435165217856
    regularize_weight: 1.904480470017849e-08
  relation_embedder:
    dropout: 0.15713585521083573
    regularize_weight: 0.00404098795939817
train:
  auto_correct: true
  batch_size: 128
  loss_arg: .nan
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 6
    threshold: 0.0001
  max_epochs: 400
  optimizer_args:
    lr: 0.09557317140459126
  type: 1vsAll
valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10

