dataset:
  name: aifb
  num_entities: 8280
  num_relations: 47
entity_ranking:
  metrics_per:
    relation_type: true
eval:
  batch_size: 256
import:
- reciprocal_relations_model
- transe
lookup_embedder:
  dim: 512
  initialize: xavier_normal_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.0006485949194635858
    uniform_:
      a: -0.45471791058488364
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
model: reciprocal_relations_model
negative_sampling:
  num_samples:
    o: 852
    s: 42
reciprocal_relations_model:
  base_model:
    type: transe
train:
  auto_correct: true
  batch_size: 128
  loss_arg: .nan
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 6
    threshold: 0.0001
  max_epochs: 400
  optimizer_args:
    lr: 0.09508720917710839
  type: negative_sampling
transe:
  entity_embedder:
    dropout: 0.0993033922611305
    normalize:
      p: -1.0
    regularize_weight: 2.1299035524553094e-07
  l_norm: 2.0
  relation_embedder:
    dropout: 0.04273664819596368
    normalize:
      p: -1.0
    regularize_weight: 3.4427788069759537e-10
valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10

