conve:
  convolution_bias: false
  entity_embedder:
    dropout: 0.3246727833328654
    regularize_weight: 3.2758801064411993e-12
  feature_map_dropout: 0.22391407216035986
  projection_dropout: 0.43867173682699095
  relation_embedder:
    dropout: 0.11339541910274253
    regularize_weight: 3.2854574459783884e-13
  round_dim: true
dataset:
  name: aifb
  num_entities: 8280
  num_relations: 47
entity_ranking:
  metrics_per:
    relation_type: true
eval:
  batch_size: 256
import:
- conve
- reciprocal_relations_model
lookup_embedder:
  dim: 256
  initialize: xavier_normal_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.00011070339794227587
    uniform_:
      a: -0.8547468908681677
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  regularize_args:
    p: 1
    weighted: true
model: reciprocal_relations_model
negative_sampling:
  implementation: batch
reciprocal_relations_model:
  base_model:
    entity_embedder:
      dim: 288
    relation_embedder:
      dim: 288
train:
  auto_correct: true
  batch_size: 256
  loss_arg: .nan
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 4
    threshold: 0.0001
  max_epochs: 400
  optimizer_args:
    lr: 0.07954143651463838
  type: 1vsAll
valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10

