KvsAll:
  label_smoothing: 0.0
  query_types:
    _po: true
    s_o: false
    sp_: true
ax_search:
  num_sobol_trials: 30
  num_trials: 30
  parameter_constraints: []
  parameters:
  - name: model
    type: choice
    values:
    - distmult
    - reciprocal_relations_model
  - is_ordered: true
    name: train.batch_size
    type: choice
    values:
    - 128
    - 256
    - 512
    - 1024
  - name: train.type
    type: fixed
    value: 1vsAll
  - name: train.optimizer
    type: choice
    values:
    - Adam
    - Adagrad
  - name: train.loss
    type: fixed
    value: bce
  - bounds:
    - 0.0003
    - 1.0
    log_scale: true
    name: train.optimizer_args.lr
    type: range
  - name: train.lr_scheduler
    type: fixed
    value: ReduceLROnPlateau
  - name: train.lr_scheduler_args.mode
    type: fixed
    value: max
  - name: train.lr_scheduler_args.factor
    type: fixed
    value: 0.95
  - name: train.lr_scheduler_args.threshold
    type: fixed
    value: 0.0001
  - bounds:
    - 0
    - 10
    name: train.lr_scheduler_args.patience
    type: range
  - is_ordered: true
    name: lookup_embedder.dim
    type: choice
    values:
    - 128
    - 256
    - 512
  - name: lookup_embedder.initialize
    type: choice
    values:
    - xavier_normal_
    - xavier_uniform_
    - normal_
    - uniform_
  - name: lookup_embedder.initialize_args.normal_.mean
    type: fixed
    value: 0.0
  - bounds:
    - 1.0e-05
    - 1.0
    log_scale: true
    name: lookup_embedder.initialize_args.normal_.std
    type: range
  - bounds:
    - -1.0
    - -1.0e-05
    name: lookup_embedder.initialize_args.uniform_.a
    type: range
  - name: lookup_embedder.initialize_args.xavier_uniform_.gain
    type: fixed
    value: 1.0
  - name: lookup_embedder.initialize_args.xavier_normal_.gain
    type: fixed
    value: 1.0
  - is_ordered: true
    name: lookup_embedder.regularize
    type: choice
    values:
    - ''
    - l3
    - l2
    - l1
  - name: lookup_embedder.regularize_args.weighted
    type: choice
    values:
    - true
    - false
  - bounds:
    - 1.0e-20
    - 0.1
    log_scale: true
    name: distmult.entity_embedder.regularize_weight
    type: range
  - bounds:
    - 1.0e-20
    - 0.1
    log_scale: true
    name: distmult.relation_embedder.regularize_weight
    type: range
  - bounds:
    - -0.5
    - 0.5
    name: distmult.entity_embedder.dropout
    type: range
  - bounds:
    - -0.5
    - 0.5
    name: distmult.relation_embedder.dropout
    type: range
  sobol_seed: 0
conve:
  2D_aspect_ratio: 2
  class_name: ConvE
  convolution_bias: true
  entity_embedder:
    +++: +++
    dropout: 0.2
    type: lookup_embedder
  feature_map_dropout: 0.2
  filter_size: 3
  padding: 0
  projection_dropout: 0.3
  relation_embedder:
    +++: +++
    dropout: 0.2
    type: lookup_embedder
  round_dim: false
  stride: 1
dataset:
  +++: +++
  files:
    +++: +++
    entity_ids:
      filename: entity_map.del
      type: map
    entity_strings:
      filename: entity_ids.del
      type: map
    relation_ids:
      filename: relation_map.del
      type: map
    relation_strings:
      filename: relation_ids.del
      type: map
    test:
      filename: test.del
      type: triples
    train:
      filename: train.del
      type: triples
    valid:
      filename: valid.del
      type: triples
  name: aifb
  num_entities: 8282
  num_relations: 47
  pickle: true
  test_size: 5845
  train_size: 17534
  valid_size: 5845
distmult:
  class_name: DistMult
  entity_embedder:
    +++: +++
    dropout: 0.4840378286316991
    regularize_weight: 0.004714602248474383
    type: lookup_embedder
  relation_embedder:
    +++: +++
    dropout: 0.13756089191883802
    regularize_weight: 1.5302293865255622e-06
    type: lookup_embedder
entity_ranking:
  chunk_size: -1
  filter_splits:
  - train
  - valid
  filter_with_test: true
  hits_at_k_s:
  - 1
  - 3
  - 10
  - 50
  - 100
  - 200
  - 300
  - 400
  - 500
  - 1000
  metrics_per:
    argument_frequency: false
    head_and_tail: false
    relation_type: true
  tie_handling: rounded_mean_rank
eval:
  batch_size: 256
  num_workers: 0
  pin_memory: false
  split: valid
  trace_level: epoch
  type: entity_ranking
grid_search:
  parameters:
    +++: +++
  run: true
import:
- distmult
- reciprocal_relations_model
job:
  device: cuda:0
  type: eval
lookup_embedder:
  class_name: LookupEmbedder
  dim: 256
  dropout: 0.0
  initialize: xavier_uniform_
  initialize_args:
    +++: +++
    normal_:
      mean: 0.0
      std: 0.004717996825882204
    uniform_:
      a: -0.6822958061070368
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  normalize:
    p: -1.0
    with_grad: false
  regularize: lp
  regularize_args:
    +++: +++
    p: 1
    weighted: false
  regularize_weight: 0.0
  round_dim_to: []
  sparse: false
manual_search:
  configurations: []
  run: true
model: distmult
negative_sampling:
  chunk_size: -1
  filtering:
    implementation: fast_if_available
    o: false
    p: false
    s: false
    split: ''
  frequency:
    smoothing: 1
  implementation: batch
  num_samples:
    o: -1
    p: 0
    s: 3
  sampling_type: uniform
  shared: false
  with_replacement: true
random_seed:
  numpy: -1
  python: -1
  torch: -1
reciprocal_relations_model:
  base_model:
    +++: +++
    type: distmult
  class_name: ReciprocalRelationsModel
search:
  device_pool:
  - cuda:0
  - cuda:1
  num_workers: 4
  on_error: abort
  type: ax
train:
  abort_on_nan: true
  auto_correct: true
  batch_size: 512
  checkpoint:
    every: 5
    keep: 3
  loss: bce
  loss_arg: 0.0
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    +++: +++
    factor: 0.95
    mode: max
    patience: 8
    threshold: 0.0001
  max_epochs: 400
  num_workers: 0
  optimizer: Adam
  optimizer_args:
    +++: +++
    lr: 0.016289859169221
  pin_memory: false
  split: train
  trace_level: epoch
  type: 1vsAll
  visualize_graph: false
user:
  +++: +++
valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10
  every: 5
  metric: mean_reciprocal_rank_filtered_with_test
  metric_expr: float("nan")
  split: valid
  trace_level: epoch
verbose: true
